### ISSUE TITLE
8 use case diagrams -- 2 per person

### ISSUE THREAD

**Issue by Dylando22** [CS-3450-Group-13/frappy#2]
1. Customer orders online -- Jacob
2. Manager pays all employees -- Jacob
3. Customer orders from cashier -- Spencer
4. Barista gets order and makes it -- Spencer
5. Cashier log in their hours -- Dalyn
6. Manager create new drink order -- Dalyn
7. User Logging in -- Dylan S
8. Manager adds/deletes employees -- Dylan S
9. Manager edits the inventory -- ???

**Comment by SeaCastle** [comment]
Finished 9/16/22
