### ISSUE TITLE
Activity Diagram -- 1

### ISSUE THREAD

**Issue by Dylando22** [CS-3450-Group-13/frappy#51]
This is for your team to look up and research syntax for a UML Activity Diagram and document your high-priority features or processes. The purpose of this is to understand more about your system and explore different ways of solving the problem. The Activity Diagrams should focus on execution flow directly related to your selected features for this sprint

**Comment by jfitzusu** [comment]
Order a drink

**Comment by SeaCastle** [comment]
Manager adds new drink
