### ISSUE TITLE
Get menu information from dan, and design the menu

### ISSUE THREAD

**Issue by SeaCastle** [CS-3450-Group-13/frappy#79]
Linking which ingredients are used in each menu item. 
- 6 standard frappys min
- 12 ingredients min
- Must include Macha

**Comment by SeaCastle** [comment]
Frappuccinos:
- Pumpkin Spice
- Caramel
- Mocha Cookie Crumble
- Macha
- Vanilla Bean
- The Diabetes Special

Ingredients:
  Milks:
    - Milk
    - Soy Milk
  Base:
    - Coffee
    - Cream
  Extras:
    - Secret Sauce
    - Vanilla
    - Caramel
    - Pumpkin Sauce
    - Mocha
    - Macha
    - Chocolate
    - Oreos
    - Sugar

**Comment by SeaCastle** [comment]
Ingredient List for Frappe's
Pumpkin Spice
- Soy Milk
- Coffee
- Pumpkin Sauce x2
- Sugar
- Whip Cream

Caramel
- Coffee
- Milk
- Caramel x2
- Sugar
- Whip Cream

Mocha Cookie Crumble
- Milk
- Cream
- Secret Sauce
- Oreos
- Whip Cream

Macha
- Soy Milk
- Cream
- Macha x3

Vanilla Bean
- Soy Milk
- Coffee
- Vanilla x3
- Chocolate Drizzle x2
- Whip Cream

The Diabetes Special
- Milk
- Cream
- Secret Sauce x3
- Vanilla
- Caramel
- Pumpkin Sauce x2
- Mocha
- Macha x2
- Chocolate Drizzle x3
- Oreos
- Sugar x4
- Whip Cream

**Comment by dalyndalton** [comment]
Fixed in latest release, now just reload the database
